In [7]:
import pandas as pd

In [22]:
df = pd.read_excel('./1. 이커머스 FC주문 데이터/1-2. 이커머스 FC주문 데이터_3월.xlsx')

### 3월 -> 309,352 rows

In [23]:
df

,CORP_ID,REF_ORD_NO,BKG_NO,BKG_TYP,BKG_DATE,BKG_TIME,SHPR_CD,INV_AMT,ITEM_SEQ,ITEM_CD,...,DLVSUBCLSFCD,INS_ID,INS_DATE,INS_TIME,POST_ZONE,SPLIT_EXEC_YN,SHPR_ADDR_1,SHPR_ADDR_2,CNEE_ADDR_1,CNEE_ADDR_2
0,KX007,2021030365922551,KX007210303370934,7,20210303,35510,90001302,22400.0,2,134265392,...,1,iNEXBatch,20210303,131425,3.0,N,세종특별자치시,NaN,서울특별시,서대문구
1,KX007,2021030365922951,KX007210303371080,7,20210303,35521,90001441,20900.0,1,4610261043_2,...,4,iNEXBatch,20210303,131425,50.0,N,경기도,광주시,경상남도,김해시
2,KX007,2021030365924361,KX007210303371081,7,20210303,35513,90001441,37900.0,1,4936599538_1,...,0,iNEXBatch,20210303,131425,53.0,N,경기도,광주시,경상남도,거제시
3,KX007,2021030365928921,KX007210303371205,7,20210303,35608,90001542,69800.0,1,3858391637_1,...,1,iNEXBatch,20210303,131425,6.0,N,경기도,광주시,서울특별시,서초구
4,KX007,2021030365930451,KX007210303370967,7,20210303,35551,90001341,73700.0,1,4631307460,...,1,iNEXBatch,20210303,131425,10.0,N,경기도,광주시,경기도,김포시
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
309347,KX007,2021040163863411,KX007210401807629,7,20210331,235554,90001582,19500.0,1,161523952_5,...,2p,iNEXBatch,20210401,174255,46.0,N,경기도,안산시,부산광역시,북구
309348,KX007,2021040163894031,KX007210401807630,7,20210331,235800,90001582,43600.0,1,4789343708_3,...,2p,iNEXBatch,20210401,174255,49.0,N,경기도,안산시,부산광역시,서구
309349,KX007,1617235699003,KX007210401806392,7,20210331,0,90001502,0.0,1,100034,...,0,BATCH,20210401,173600,21.0,N,경기,광주시,인천광역시,NaN
309350,KX007,1617235754497,KX007210401806393,7,20210331,0,90001502,0.0,1,100032,...,2,BATCH,20210401,173600,16.0,N,경기,광주시,경기도,NaN
309351,KX007,2103291504517216,KX007210401807071,7,20210329,150451,90001502,0.0,1,100240,...,0,BATCH,20210401,180601,57.0,N,경기,광주시,전라남도,NaN

In [28]:
spool = df.groupby('BKG_DATE').count()['CORP_ID']

In [36]:
df_col = ['x','y']
df_list =[]
for i , j in zip(spool.index.tolist(),spool.tolist()):
    df_list = [i-20210300,j]

In [38]:
df_result = pd.DataFrame('')

[8536,
 11912,
 13756,
 10330,
 12929,
 5512,
 6538,
 7912,
 7223,
 7004,
 8486,
 6025,
 5943,
 8464,
 8123,
 10051,
 7343,
 6507,
 6529,
 5856,
 8454,
 22070,
 31009,
 9578,
 9379,
 15108,
 7824,
 9278,
 12158,
 9179,
 10336]